version = "2"

[linters]
default = "none"
enable = [
    "asciicheck",
    "bodyclose",
    "cyclop",
    "depguard",
    "dogsled",
    "dupl",
    "durationcheck",
    "errcheck",
    "errorlint",
    "exhaustive",
    "forbidigo",
    "funlen",
    "gochecknoinits",
    "goconst",
    "gocritic",
    "goheader",
    "gomodguard",
    "goprintffuncname",
    "gosec",
    "govet",
    "importas",
    "ineffassign",
    "lll",
    "makezero",
    "misspell",
    "nakedret",
    "nilerr",
    "noctx",
    "nolintlint",
    "prealloc",
    "predeclared",
    "revive",
    "rowserrcheck",
    "sqlclosecheck",
    "staticcheck",
    "thelper",
    "tparallel",
    "unconvert",
    "unparam",
    "unused",
    "usetesting",
    "wastedassign",
    "whitespace",
]

[linters.settings.exhaustive]
default-signifies-exhaustive = true

[[linters.exclusions.rules]]
path = ".test.go"
linters = ["funlen", "goconst", "gosec"]

[[linters.exclusions.rules]]
path = "main.go"
linters = ["forbidigo"]

[formatters]
enable = [
    "gci",
    "gofmt",
    "gofumpt",
    "goimports",
]
