# This is a TOML document. Boom.
title = "TOML Example"

[clients]
  data = [["gamma","delta"],[1,2]] # just an update to make sure parsers support it

[database]
  connection_max = 5000
  enabled = true
  ports = [8001,8001,8002]
  server = "192.168.1.1"

[owner]
  bio = "GitHub Cofounder & CEO\nLikes tater tots and beer."
  dob = 1979-05-27T07:32:00Z # First class dates? Why not?
  name = "Tom Preston-Werner"
  organization = "GitHub"

[servers]
  # You can indent as you please. Tabs or spaces. TOML don't care.

  [servers.alpha]
    dc = "eqdc10"
    ip = "10.0.0.1"

  [servers.beta]
    dc = "eqdc10"
    ip = "10.0.0.2"
