name: docker
on:
  pull_request:
    branches:
      - v2

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
