name: Fuzzit
on: [push]
jobs:
  fuzzing:
    name: Run fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@v1
      - run: echo '##[add-path]/home/runner/go/bin'
      - run: ./fuzzit.sh
        env:
          TYPE: fuzzing
