name: Fuzzit
on:
  push:
    branches:
      - master
jobs:
  fuzzing:
    name: Run fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@v1
      - name: Add GOPATH/bin to PATH
        run: echo '##[add-path]/home/runner/go/bin'
      - name: Copy source to GOPATH/src
        run: mkdir -p ${TARGET} && cp -R . ${TARGET}/
        env:
          TARGET: /home/runner/go/src/github.com/pelletier/go-toml
      - run: ./fuzzit.sh
        env:
          TYPE: fuzzing
          FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
