name: test
on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        go: [ '1.15', '1.16' ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.go }}/${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - name: Run unit tests
        run: go test -race ./...
